
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 25
force_explicit_abi = false
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "Vertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_try_shorthand = true
wrap_comments = true
